on:
  push:
  workflow_dispatch:
env:
  CI_COMMIT_SHA: ${{ github.sha }}
jobs:
  print-tag:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Print the input tag to STDOUT
        run: |
          echo "COMMIT_SHA_SHORT=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      - name: run
        run: |
          echo "${{ env.COMMIT_SHA_SHORT }}"
          env || grep "COMMIT"
      - name: ruuuuuu
        run: |
          # Python script to shorten the SHA to 7 characters
          python3 -c "
import os
commit_sha = os.getenv('CI_COMMIT_SHA', '')[:7]
print(f'SHORT_SHA={commit_sha}')
" > .env
          source .env
          echo "Shortened SHA: $SHORT_SHA"
      - name: pr
        run: |
          env || grep "SHORT"
          echo ${SHORT_SHA}
          
