on:
  push:
  workflow_dispatch:
jobs:
  print-tag:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Print the input tag to STDOUT
        run: |
          cal=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHA_SHORT=$cal" >> $GITHUB_ENV
          echo ${{ env.COMMIT_SHA_SHORT }}
          env
