on:
  push:
  workflow_dispatch:
env:
  CI_COMMIT_SHA: ${{ github.sha }}
jobs:
  print-tag:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Print the input tag to STDOUT
        run: |
          echo "COMMIT_SHA_SHORT=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      - name: run
        run: |
          echo "${{ env.COMMIT_SHA_SHORT }}"
          env || grep "COMMIT"
      - name: Set SHORT_SHA
        id: set_short_sha
        run: |
          SHORT_SHA=$(python3 -c "print(''[:7])")
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
      - name: pr
        run: |
          env || grep "SHORT"
          echo ${{ env.SHORT_SHA }}
      - name: Set SHORT_SHA using bash
        run: |
          SHORT_SHA_1=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "SHORT_SHA_BASH=$SHORT_SHA_1" >> $GITHUB_ENV
      - name: Show bash sha
        run: |
          echo "${{ env.SHORT_SHA_BASH }}"
          
