on:
  push:
  workflow_dispatch:
jobs:
  print-tag:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Print the input tag to STDOUT
        run: |
          echo "COMMIT_SHA_SHORT=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      - name: run
        run: |
          echo "${{ env.COMMIT_SHA_SHORT }}"
          env || grep "COMMIT"
